<?php
require("connect.php");
session_start();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">

</script>
</head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>RAS: Home</title>
<meta name="keywords" content="Active Website, Free CSS Template, HTML CSS" />
<meta name="description" content="aaebsite - Free CSS Template provided by templatemo.com" />
<link href="templatemo_style.css" rel="stylesheet" type="text/css" />


	<title>Slider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image slider" />
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>

	<!-- End WOWSlider.com HEAD section -->
	
</head>
<body> 
<form method='POST'>
<div id="templatemo_wrapper">
    <div id="templatemo_header">
		<img src="RASpics/banner.jpg" width='970' height='170'/>
		
		    <div id="templatemo_menu">
                
            <ul>
                <li><a href="index.php" class="current">Home</a></li>
                <li><a href="about.php">About Us</a></li>
                <li><a href="contactus.php">Contact Us</a></li>
                <li><a href="admissions.php">Admissions</a></li>
                <li><a href="gallery.php">Gallery</a></li>
				<li><a href="myportal.php">My Portal</a></li>
				<li><a href="alumni.php">Alumni</a></li>
				<li><a href="faq.php">FAQ</a></li>
          	</ul>   	
        
        </div> <!-- end of templatemo_menu -->

  </div> <!-- end of header -->
   
	
	
    <div id="templatemo_middle">
	
			<div id="comslider_in_point_334359" style="padding-left:0.5cm;padding-top:0.3cm;"></div>
				<script type="text/javascript">

				var oCOMScript334359=document.createElement('script');
				oCOMScript334359.src="comslider334359/comsliderd.js?timestamp=1409417257";
				oCOMScript334359.type='text/javascript';
				document.getElementsByTagName("head").item(0).appendChild(oCOMScript334359);
				</script>
	
			
			<div style="float:right;padding-right:1cm;margin-top:-11cm;">
				<img src="RASpics/welcome.jpg" width='326' height='70' align="bottom"/>
			</div>
			
	        <p style="padding-left:17cm;height:250px;text-align:justify;margin-top:-9cm;">
			
			
				RAES is awarded a 4-year accreditation by the internationally recognized Adventist Accrediting Association (AAA) with headquarters at Silver Spring, Maryland, USA.
			<br></br>RAHS is an ESC-EVS participating school and has been enjoying financial grants from Fund for Assistance to Private Education (FAPE).
			<br></br><i><b>Christian Education at its BEST! A Journey to Excellence! Enroll now at Rosario Adventist School..</i></b>
			
			</p>
            
          <div class="button float_r" style = "float: right;padding-right:0.5cm;margin-top:-3cm;"><a href="about.php">Learn More</a></div>
            

			
			<div style="float:right;padding-right:4cm;margin-top:-3cm;">
				<img src="RASpics/123.jpg" width='74' height='79' align="bottom"/>
			</div>
			
`<br></br>
      
    </div>
    <div id="templatemo_main">
 
    	<div id="templatemo_content" style="text-align:center;">
		

            <h3 style="color: #2E8B57;margin-top:0.1cm;"><b>FEATURED NEWS</h2></b>
			
			<?php
					$q1=mysql_query("SELECT newsid, substring(newscontent,1,90) As newscontent, newstitle FROM newsevents WHERE newscategory='news' LIMIT 3") or die(mysql_error());
							
					while($r=mysql_fetch_array($q1))
					{
						$newsid=$r['newsid'];
						$newstitle=$r['newstitle'];
						$newscontent=$r['newscontent'];
						
						echo "<h4>".$newstitle."</h4>";
						?>
						
						<p><?php echo $newscontent; ?>...<a href="news.php?newsid=<?php echo $newsid; ?>"> read more </a></p>
							 <div class="cleaner_h20 horizon_divider"></div>
            <div class="cleaner_h20"></div>
			<?php
					}
					echo "<br>";					
				?>
		</div>
		
		<div id="templatemo_content2" style="text-align:center;">
			<h3 style="color: #2E8B57;margin-top:0.1cm;"><b>RECENT EVENTS</h2></b>
			
			<?php
					$q1=mysql_query("SELECT newsid, substring(newscontent,1,80) As newscontent, newstitle,newsimage FROM newsevents WHERE newscategory='events' LIMIT 3") or die(mysql_error());
							
					while($r=mysql_fetch_array($q1))
					{
						$newsid=$r['newsid'];
						$newstitle=$r['newstitle'];
						$newscontent=$r['newscontent'];
						//$newsimage=$r['newsimage'];
						echo '<img style="width:150px;height:69px;margin-top:-0.2cm;" src="data:image/jpeg;base64,'.base64_encode( $r['newsimage'] ).'"/>';
						echo "<h4>".$newstitle."</h4>";
							 ?>
							 <p style="margin-top:-0.2cm;"><?php echo $newscontent; ?>...<a href="events.php?newsid=<?php echo $newsid; ?>"> read more </a></p>
						
							 <div class="cleaner_h20 horizon_divider" style="margin-top:-0.4cm;"></div>
            <div class="cleaner_h20"></div>
			<?php
					}
				?>
			
		</div>
		<div id="templatemo_content3" style="text-align:center;">
	   
			<h3 style="color: #2E8B57;margin-top:0.1cm;"><b>LET US KNOW...</h2></b>
			<h6 align="justify"><b>Inquire Now!</h6></b>
			<p align="left";>﻿Inquire about upcoming events and learn how to join:</p>
			
			<form action="contactus_addinfo.php "method="post">
                
                        <input type="hidden" name="post" value="Send" />
                      	<label for="Name">Name:</label> <input type="text" id="Name" name="Name" class="required input_field" />
                      	<div class="cleaner_h10"></div>
                        
                        <label for="Email">Email:</label> <input type="text" id="Email" name="Email" class="validate-email required input_field"/>
                      	<div class="cleaner_h10"></div>

                        <label for="Message">Message:</label> <textarea id="Message" name="Message" rows="2" cols="18" class="required"></textarea>
                        <div class="cleaner_h10"></div>
                        
                        <input type="submit" class="submit_btn" name="submit" id="submit" value="Send" />
                        <input type="reset" class="submit_btn" name="reset" id="reset" value="Reset" />
						<br></br>
				</form>			
				
				<h4 style="text-align:left;color: #2E8B57;">RAS Address</h3>
				<p style="text-align:left;line-height: 100%;">Gualberto Ave. Brgy. Namunga, <br></br>
				Rosario, Batangas</p>
				
				<br></br>
				<h4 style="text-align:left;margin-top:-0.8cm;color: #2E8B57;">Phone Number(s)</h3>
				<?php
					$q1=mysql_query("SELECT contactno FROM schoolinfo") or die(mysql_error());
							
					while($r=mysql_fetch_array($q1))
					{
						$contactno=$r['contactno'];
						
						
						echo "<p style=\"text-align:left;line-height: 100%;\">#".$contactno."</p>";
					}			

				?>

				<h4 style="text-align:left;color: #2E8B57;line-height: 200%;">Follow Us</h3>
	
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<tr><tr><br>
	<div class="fb-like" style="line-height: 200%;margin-top:-0.8cm;" data-href="https://www.facebook.com/RosarioAdventistSchool" 
	data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
	<br></br>

				</div>
	</div>
        
    	<div class="cleaner"></div>
		
    </div>

</div> <!-- end of wrapper -->

<div id="templatemo_footer_wrapper">
	<center><img src="RASpics/footer_details.jpg" width='990' height='339'/>
	        <ul>
                <a href="index.php" class="current">Home</a>
               | <a href="about.php">About Us</a>
               | <a href="contactus.php">Contact Us</a>
               | <a href="admissions.php">Admissions</a>
               | <a href="gallery.php">Gallery</a>
			   | <a href="myportal.php">My Portal</a>
			   | <a href="alumni.php">Alumni</a>
			   | <a href="faq.php">FAQ</a>
          	</ul>   
	</center>
	
     <div id="templatemo_footer" style="font-size:11px; line-height: 120%; word-spacing: 0px;">
	 
		<b>Rosario Adventist School, Batangas 
		<br>
		Gualberto Ave. Namunga, Rosario Batangas
		<br>
		Copyright © 2013 Rosario Adventist School 
		<br>
		All rights reserved.</b>
    
    </div> </style> <!-- end of templatemo_footer -->
    
</div>

</form>
</body>
</html>
